name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt 

      - name: Run Model Unit Tests
        run: make model-test
      
      - name: Run API Unit Tests
        run: make api-test
      
      - name: Install Pylint
        run: pip install pylint
      
      - name: Pylint scan
        run: pylint **/*.py --exit-zero